### ISSUE TITLE
update rte@3.0.0 for generated scaffolds

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx-wct-scaffolder#2]
@jtrs commented on [Tue Feb 27 2018](https://github.com/cubbles/cubx-grunt-wct-scaffolder/issues/1)

---

@jtrs commented on [Tue Feb 27 2018](https://github.com/cubbles/cubx-grunt-wct-scaffolder/issues/1#issuecomment-368876199)

Add  modelVersion9.x (for devtools 2.x) and modelVersion 10.x (for devtools 3.0*)

**tasks:**
- [x] create new gitgflow branch strucutre in `cubx-wct-scaffolder` and `cubx-grunt-wct-scaffolder`
- [x] in new `develop` branch please adjust used RTE Version to 3.0 (including the webcomponents polyfill refernce, see `cubx-grunt-webpackage-scaffold`)

**Comment by edwingamboa** [comment]
Initial 3.0.0 releases were performed
